export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const LOG_OUT = 'LOG_OUT';
export const ROOT_CHANGE_REQUEST = 'ROOT_CHANGE_REQUEST';
export const ROOT_CHANGED = 'ROOT_CHANGED';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_START = 'LOAD_QUESTIONS_START';
export const LOAD_QUESTIONS_SUCCESS = 'QUESTIONS_LOAD_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'QUESTIONS_LOAD_ERROR';
